package com.threey.guard.base.domain;

public class PageStyle {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column page_style.MID
     *
     * @abatorgenerated Tue Aug 25 11:02:14 CST 2015
     */
    private String mid;
    private String name;
    
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column page_style.STYLE
     *
     * @abatorgenerated Tue Aug 25 11:02:14 CST 2015
     */
    private String style;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column page_style.MID
     *
     * @return the value of page_style.MID
     *
     * @abatorgenerated Tue Aug 25 11:02:14 CST 2015
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column page_style.MID
     *
     * @param mid the value for page_style.MID
     *
     * @abatorgenerated Tue Aug 25 11:02:14 CST 2015
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column page_style.STYLE
     *
     * @return the value of page_style.STYLE
     *
     * @abatorgenerated Tue Aug 25 11:02:14 CST 2015
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column page_style.STYLE
     *
     * @param style the value for page_style.STYLE
     *
     * @abatorgenerated Tue Aug 25 11:02:14 CST 2015
     */
    public void setStyle(String style) {
        this.style = style;
    }
}